apiVersion: "sparkoperator.hpe.com/v1beta2"
kind: SparkApplication
metadata:
  name: ezaf-airflow-data-transfer-csv-to-parquet-demo
  namespace: spark
spec:
  sparkConf:
    spark.hadoop.fs.s3a.endpoint: "13.56.82.84:31900"
    spark.hadoop.fs.s3a.access.key: "minioadmin"
    spark.hadoop.fs.s3a.secret.key: "minioadmin"
    spark.hadoop.fs.s3a.path.style.access: "true"
    spark.hadoop.fs.s3a.impl: "org.apache.hadoop.fs.s3a.S3AFileSystem"
    spark.hadoop.fs.s3a.connection.ssl.enabled: "true"
    spark.mapr.user.secret: spark-user-secret
    "spark.driver.extraJavaOptions": "-Dcom.amazonaws.sdk.disableCertChecking=true"
    "spark.executor.extraJavaOptions": "-Dcom.amazonaws.sdk.disableCertChecking=true"
  type: Scala
  sparkVersion: 3.2.0
  mode: cluster
  image: gcr.io/mapr-252711/spark-demo-example:v1.0
  imagePullPolicy: Always
  mainApplicationFile: local:///tmp/DataProcessTransfer.jar
  mainClass: com.mapr.sparkdemo.DataProcessTransfer
  arguments:
    - s3a://ezaf-demo/data/financial.csv
    - csv
    - file:///mounts/data/financial-processed
    - parquet
  restartPolicy:
    type: Never
  imagePullSecrets:
    - hpe-imagepull-secrets
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 3.2.0
    volumeMounts:
      - mountPath: /mounts/data/
        name: spark-data
    serviceAccount: hpe-{{params.namespace}}
  executor:
    cores: 1
    instances: 2
    memory: "512m"
    labels:
      version: 3.2.0
    volumeMounts:
      - mountPath: /mounts/data
        name: spark-data
  volumes:
    - name: spark-data
      persistentVolumeClaim:
        claimName:  {{dag_run.conf.get("username", "mohan-rajagopalan")}}-spark-pvc
